physics_model: 'datasets/Molenkamp' # this is the Path to a directory for the training on a given dataset
description: 'VAE/try_KL_1.0/' #for a given dataset, one can train with different hyperparameters, hence the 'description'
epochs: 5000 #maximum number of epochs
learning_rate: 0.001 #initial learning rate
loss_coefficients: [1, 1.0] #first one is reconstruction error, second one is the regularization term. For AE it is jusdt L1 norm, for VAE it is KL divergence
lambda_regularization_strength: 0.0014 #initial coeffient of the regularization term, then increased dinamically during training
dim_input: [1, 2]  # first dimension is # of channels (one if the predicted solution is a scalar field), second is spatial dimensions per channel.
gamma_lr: 0.999 # gamma of  tc.optim.lr_scheduler.ExponentialLR()
checkpoint: false  # if true uses existing checkpoint
batch_size : 16 # batch size
time_of_AE: 10 # number of initial epochs where only the AutoEncoder is trained, i.e., loss_coeff_TF_AR_together = [1, 0, 0, 0]. In parallel of this a linear warm-up of the learning rate is performed
clipping: [0, 2.5] #[if 1 clipping is applied to f, maximum norm allowed to gradients]
side_size : 128 # length of each dimension of the input field
AutoEncoder : "VAE" # defines the type of AutoEncoder used: if 'VAE' a Variational Autoencoder will be used, otherwise a standard AutoEncoder.
which_device : 'cuda:1' #device where to train
num_workers : 8 #number of workers of dataloaders
data_path : '../../../../../scratch/aalelonghi/molenkamp_whole_time_series/' #path of training and validation data
normalization_field_ma : [True, 1.0] # if true, maxima of each dimension of the solution fields are found. If not, dimension 1,2, etc are the maxima of dimension 1,2, etc of the solution field (only one if it is a scalar field)
normalization_field_mi : [True, 0.0] # if true, minima of each dimension of the solution fields are found. If not, dimension 1,2, etc are the minima of dimension 1,2, etc of the solution field (only one if it is a scalar field)