kernel_enc: [5, 5, 3, 3, 3, 3, 3] #kernels sizes of the Encoder
filters_enc: [8, 16, 32, 32, 32, 32, 2] #number of filters of the Encoder
stride_enc: [1, 2, 2, 2, 2, 1, 1] #strides of the Encoder
latent_dim: 10 #dimension of the latent space
kernel_deco: [3, 4, 4, 4, 4, 3, 3, 3] #kernels sizes of the Decoder
number_channels_input_cnns_deco : 2
filters_deco: [32, 32, 32, 32, 32, 16, 2] #number of filters of the Decoder. Last one must be 2 for means anche variances
stride_dec: [1, 2, 2, 2, 2, 1, 1, 1] #strides of the Decoder
final_and_initial_activation: false #if true, after the final linear layer of the encoder and the initial linear layer of the decoder an activation function is used